### PR TITLE
JSON API: Set status code, replace magic numbers with human-readable constants

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by P5vc** [comment]
Are you satisfied with these changes? If so, I will go ahead and merge them.

**Comment by elimisteve** [comment]
Ha come on man, being in favor of extra parens is one thing -- that's stylistic, so OK -- but you're also against using helper functions that help get rid of duplicate/boilerplate code? Why nuke the `JsonResponse` helper?

**Comment by P5vc** [comment]
Not at all, I love helper functions!

In this case however, I don't think the extra function is necessary. Normally, when creating a helper function, I'll do it to increase readability, increase efficiency, or to simplify/shorten the code.

Please let me know if you disagree or if there's another argument for the helper function that I should consider, but in this case, I don't think it contributes to any of the above, because:

- No Increased Readability
  - The helper function doesn't group together any related code or serve any purpose but to add an extra argument to the object instantiation. This is a bit redundant, because that argument could just be added to the instantiation from the beginning: there's no need to define an entire function just to add one, additional argument, especially when that argument has no further operations being performed on it. My concern is that this could confuse other programmers as to why the extra function is needed, or at the very least, will have them searching through the code to locate the local function, when instead, the Django object could just be directly instantiated in the first place. They could also be confused that we've defined a local function with the same name as the Django class.
- No Increased Efficiency
  - The extra function call adds a bit of inefficiency. This tradeoff is admittedly almost negligible, and if the function served any purpose other than to return an instantiated response object (the same operation that this function call replaces), I would have no problem ignoring that, however it's still something to think about.
- No Code Shortening or Simplification
  - This extra function only adds more lines of code, and provides a roundabout way of returning a response object, which to me seems a bit more complex than just returning the object directly in the first place. It seems to me like it would read clearer to only have one line containing all of the arguments, than to have to return the object returned from the function called to instantiate the object with all of the arguments.

I hope that makes sense, and please don't hesitate to let me know if you disagree! It's very possible I misunderstood your intentions.

Also, thanks again for contributing and making these pull requests! They're very insightful and only help to make Priveasy better! :)

**Comment by P5vc** [comment]
@elimisteve Are you okay if I go ahead and merge this? Thanks!

**Comment by P5vc** [comment]
Alright, I haven't heard back in about a month, so I'm going to go ahead and merge this. Thank you so much for your contribution!

**Pull request merged**
